### ISSUE TITLE
How do you fill up the database?

### ISSUE THREAD

**Issue by j0k3r** [KuiKui/Octoboard#1]
Hi there,

I was curious to see how to you implement a query using Google BigQuery but finally there is nothing related to this in the project.
I see the sql file to put some data in the database, but how do you fill up the database on a daily basis ?

Thanks

**Comment by KuiKui** [comment]
Hi,

I launch [this script](https://github.com/KuiKui/Octoboard/blob/master/scripts/importArchives.php) once a day on my server.
The SQL file is just a backup.

**Comment by j0k3r** [comment]
Oh ok. And why it's not a symfony task?

**Comment by KuiKui** [comment]
Good question ;-)
I will do it soon.

**Comment by j0k3r** [comment]
:-)
